imagenet_dict = {0: ["tench", "Tinca tinca"],
                 1: ["goldfish", "Carassius auratus"],
                 2: ["great white shark", "white shark", "man-eater", "man-eating shark", "Carcharodon carcharias"],
                 3: ["tiger shark", "Galeocerdo cuvieri"],
                 4: ["hammerhead", "hammerhead shark"],
                 5: ["electric ray", "crampfish", "numbfish", "torpedo"],
                 6: ["stingray"],
                 7: ["cock"],
                 8: ["hen"],
                 9: ["ostrich", "Struthio camelus"],
                 10: ["brambling", "Fringilla montifringilla"],
                 11: ["goldfinch", "Carduelis carduelis"],
                 12: ["house finch", "linnet", "Carpodacus mexicanus"],
                 13: ["junco", "snowbird"],
                 14: ["indigo bunting", "indigo finch", "indigo bird", "Passerina cyanea"],
                 15: ["robin", "American robin", "Turdus migratorius"],
                 16: ["bulbul"],
                 17: ["jay"],
                 18: ["magpie"],
                 19: ["chickadee"],
                 20: ["water ouzel", "dipper"],
                 21: ["kite"],
                 22: ["bald eagle", "American eagle", "Haliaeetus leucocephalus"],
                 23: ["vulture"],
                 24: ["great grey owl", "great gray owl", "Strix nebulosa"],
                 25: ["European fire salamander", "Salamandra salamandra"],
                 26: ["common newt", "Triturus vulgaris"],
                 27: ["eft"],
                 28: ["spotted salamander", "Ambystoma maculatum"],
                 29: ["axolotl", "mud puppy", "Ambystoma mexicanum"],
                 30: ["bullfrog", "Rana catesbeiana"],
                 31: ["tree frog", "tree-frog"],
                 32: ["tailed frog", "bell toad", "ribbed toad", "tailed toad", "Ascaphus trui"],
                 33: ["loggerhead", "loggerhead turtle", "Caretta caretta"],
                 34: ["leatherback turtle", "leatherback", "leathery turtle", "Dermochelys coriacea"],
                 35: ["mud turtle"],
                 36: ["terrapin"],
                 37: ["box turtle", "box tortoise"],
                 38: ["banded gecko"],
                 39: ["common iguana", "iguana", "Iguana iguana"],
                 40: ["American chameleon", "anole", "Anolis carolinensis"],
                 41: ["whiptail", "whiptail lizard"],
                 42: ["agama"],
                 43: ["frilled lizard", "Chlamydosaurus kingi"],
                 44: ["alligator lizard"],
                 45: ["Gila monster", "Heloderma suspectum"],
                 46: ["green lizard", "Lacerta viridis"],
                 47: ["African chameleon", "Chamaeleo chamaeleon"],
                 48: ["Komodo dragon", "Komodo lizard", "dragon lizard", "giant lizard", "Varanus komodoensis"],
                 49: ["African crocodile", "Nile crocodile", "Crocodylus niloticus"],
                 50: ["American alligator", "Alligator mississipiensis"],
                 51: ["triceratops"],
                 52: ["thunder snake", "worm snake", "Carphophis amoenus"],
                 53: ["ringneck snake", "ring-necked snake", "ring snake"],
                 54: ["hognose snake", "puff adder", "sand viper"],
                 55: ["green snake", "grass snake"],
                 56: ["king snake", "kingsnake"],
                 57: ["garter snake", "grass snake"],
                 58: ["water snake"],
                 59: ["vine snake"],
                 60: ["night snake", "Hypsiglena torquata"],
                 61: ["boa constrictor", "Constrictor constrictor"],
                 62: ["rock python", "rock snake", "Python sebae"],
                 63: ["Indian cobra", "Naja naja"],
                 64: ["green mamba"],
                 65: ["sea snake"],
                 66: ["horned viper", "cerastes", "sand viper", "horned asp", "Cerastes cornutus"],
                 67: ["diamondback", "diamondback rattlesnake", "Crotalus adamanteus"],
                 68: ["sidewinder", "horned rattlesnake", "Crotalus cerastes"],
                 69: ["trilobite"],
                 70: ["harvestman", "daddy longlegs", "Phalangium opilio"],
                 71: ["scorpion"],
                 72: ["black and gold garden spider", "Argiope aurantia"],
                 73: ["barn spider", "Araneus cavaticus"],
                 74: ["garden spider", "Aranea diademata"],
                 75: ["black widow", "Latrodectus mactans"],
                 76: ["tarantula"],
                 77: ["wolf spider", "hunting spider"],
                 78: ["tick"],
                 79: ["centipede"],
                 80: ["black grouse"],
                 81: ["ptarmigan"],
                 82: ["ruffed grouse", "partridge", "Bonasa umbellus"],
                 83: ["prairie chicken", "prairie grouse", "prairie fowl"],
                 84: ["peacock"],
                 85: ["quail"],
                 86: ["partridge"],
                 87: ["African grey", "African gray", "Psittacus erithacus"],
                 88: ["macaw"],
                 89: ["sulphur-crested cockatoo", "Kakatoe galerita", "Cacatua galerita"],
                 90: ["lorikeet"],
                 91: ["coucal"],
                 92: ["bee eater"],
                 93: ["hornbill"],
                 94: ["hummingbird"],
                 95: ["jacamar"],
                 96: ["toucan"],
                 97: ["drake"],
                 98: ["red-breasted merganser", "Mergus serrator"],
                 99: ["goose"], }

cifar100_dict = {19: 'cattle', 29: 'dinosaur', 0: 'apple', 11: 'boy', 1: 'aquarium_fish', 86: 'telephone', 90: 'train',
                 28: 'cup', 23: 'cloud', 31: 'elephant', 39: 'keyboard', 96: 'willow_tree', 82: 'sunflower',
                 17: 'castle', 71: 'sea', 8: 'bicycle', 97: 'wolf', 80: 'squirrel', 74: 'shrew', 59: 'pine_tree',
                 70: 'rose', 87: 'television', 84: 'table', 64: 'possum', 52: 'oak_tree', 42: 'leopard',
                 47: 'maple_tree', 65: 'rabbit', 21: 'chimpanzee', 22: 'clock', 81: 'streetcar', 24: 'cockroach',
                 78: 'snake', 45: 'lobster', 49: 'mountain', 56: 'palm_tree', 76: 'skyscraper', 89: 'tractor',
                 73: 'shark', 14: 'butterfly', 9: 'bottle', 6: 'bee', 20: 'chair', 98: 'woman', 36: 'hamster',
                 55: 'otter', 72: 'seal', 43: 'lion', 51: 'mushroom', 35: 'girl', 83: 'sweet_pepper', 33: 'forest',
                 27: 'crocodile', 53: 'orange', 92: 'tulip', 50: 'mouse', 15: 'camel', 18: 'caterpillar', 46: 'man',
                 75: 'skunk', 38: 'kangaroo', 66: 'raccoon', 77: 'snail', 69: 'rocket', 95: 'whale', 99: 'worm',
                 93: 'turtle', 4: 'beaver', 61: 'plate', 94: 'wardrobe', 68: 'road', 34: 'fox', 32: 'flatfish',
                 88: 'tiger', 67: 'ray', 30: 'dolphin', 62: 'poppy', 63: 'porcupine', 40: 'lamp', 26: 'crab',
                 48: 'motorcycle', 79: 'spider', 85: 'tank', 54: 'orchid', 44: 'lizard', 7: 'beetle', 12: 'bridge',
                 2: 'baby', 41: 'lawn_mower', 37: 'house', 13: 'bus', 25: 'couch', 10: 'bowl', 57: 'pear', 5: 'bed',
                 60: 'plain', 91: 'trout', 3: 'bear', 58: 'pickup_truck', 16: 'can'}
cifar10_dict = {0: 'airplane', 1: 'automobile', 2: 'bird', 3: 'cat', 4: 'deer',
                5: 'dog', 6: 'frog', 7: 'horse', 8: 'ship', 9: 'truck'}
